### PR TITLE
bindgen generation wrapper for cli use

### PR DESCRIPTION
**Pull request by dginev**
Bundles in a script that allows for directly regenerating `src/bindings.rs` via:
```
bindgen scripts/bindgen_wrapper.h -o src/bindings.rs -- `xml2-config --cflags`
```

Some steps towards #73

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
So I have tried using this approach, but it does not really work on my laptop (x86_64):

```rust
error[E0308]: mismatched types
   --> src/c_helpers.rs:109:57
    |
109 |     xmlSetStructuredErrorFunc(ctxt as *mut c_void, Some(_ignoreInvalidTagsErrorFunc));
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected "C" fn, found "Rust" fn
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _)`
                  found fn item `fn(_, _) {c_helpers::_ignoreInvalidTagsErrorFunc}`

error[E0308]: mismatched types
  --> src/schemas/parser.rs:82:14
   |
82 |         Some(common::structured_error_handler),
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected "C" fn, found "Rust" fn
   |
   = note: expected fn pointer `unsafe extern "C" fn(_, _)`
                 found fn item `fn(_, _) {schemas::common::structured_error_handler}`

error[E0308]: mismatched types
   --> src/schemas/validation.rs:104:14
    |
104 |         Some(common::structured_error_handler),
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected "C" fn, found "Rust" fn
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _)`
                  found fn item `fn(_, _) {schemas::common::structured_error_handler}`
```

**Comment by ignatenkobrain** [comment]
and also:

```rust
error[E0425]: cannot find value `HACKY_WELL_FORMED` in this scope
   --> src/c_helpers.rs:101:7
    |
101 |       HACKY_WELL_FORMED = true;
    |       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `HACKY_WELL_FORMED` in this scope
   --> src/c_helpers.rs:108:5
    |
108 |     HACKY_WELL_FORMED = false;
    |     ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `HACKY_WELL_FORMED` in this scope
   --> src/c_helpers.rs:114:59
    |
114 |   unsafe { (!ctxt.is_null() && (*ctxt).wellFormed > 0) || HACKY_WELL_FORMED }
    |                                                           ^^^^^^^^^^^^^^^^^ not found in this scope

```

**Comment by ignatenkobrain** [comment]
FYI, I use `libxml2-2.9.10-4.fc33.x86_64`

**Comment by ignatenkobrain** [comment]
It seems that `HACKY_WELL_FORMED` is something what exists just in your copy of libxml2. Google does not seem to know about such constant anywhere else :)

**Comment by ignatenkobrain** [comment]
`bindgen --raw-line "#![allow(non_camel_case_types)]" --raw-line "/* helper var until we figure out well-formedness checks */" --raw-line "pub static mut HACKY_WELL_FORMED: bool = false;" --whitelist-function "(xml|html|xlink).+" --whitelist-var "(XML|HTML).+" --whitelist-type "(xml|html).+" --ctypes-prefix libc scripts/bindgen_wrapper.h -o src/bindings.rs -- -I/usr/include/libxml2` is able to give something actually meaningful :)

**Comment by ignatenkobrain** [comment]
With this bindgen command, I am down to just one relevant failure:

```rust
error[E0308]: mismatched types
   --> src/c_helpers.rs:109:57
    |
109 |     xmlSetStructuredErrorFunc(ctxt as *mut c_void, Some(_ignoreInvalidTagsErrorFunc));
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected "C" fn, found "Rust" fn
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _)`
                  found fn item `fn(_, _) {c_helpers::_ignoreInvalidTagsErrorFunc}`

error[E0308]: mismatched types
  --> src/schemas/parser.rs:82:14
   |
82 |         Some(common::structured_error_handler),
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected "C" fn, found "Rust" fn
   |
   = note: expected fn pointer `unsafe extern "C" fn(_, _)`
                 found fn item `fn(_, _) {schemas::common::structured_error_handler}`

error[E0308]: mismatched types
   --> src/schemas/validation.rs:104:14
    |
104 |         Some(common::structured_error_handler),
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected "C" fn, found "Rust" fn
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, _)`
                  found fn item `fn(_, _) {schemas::common::structured_error_handler}`

error: aborting due to 3 previous errors
```

**Comment by dginev** [comment]
Hi @ignatenkobrain , 

I realize the PR is not completed, as I mentioned just "some steps" towards a solution. The traces are a bit distracting here to be honest, as much as I like the friendly messages of rustc. As you noticed, `c_helpers.rs` needs to receive some of the non-bindgen content from `bindings.rs`, at which point we can hope it's a simple swap.

**Comment by dginev** [comment]
Actually I'll close to avoid the wrong impression that I'm planning on working on this further myself. The general problem remains  unsolved.

**Pull request closed without merging**
