### PR TITLE
#72-add-vcpkg-optional-dependency

### PR DESCRIPTION
**Pull request by JoshuaNitschke**
add opt in dependency for vcpkg
make pkg-config optional but default

### CODE REVIEW

**Comment by dginev** [comment]
Thanks, this looks great! Is there some smart trick to make vcpkg default if the current OS is windows? Would be great to have the windows builds succeed by default. Happy to merge here in either case, definitely a great upgrade.

**Comment by JoshuaNitschke** [comment]
@dginev - updated.  I clones this commit, ran `cargo test`, and it built on:
- Windows 10
- WSL (Debian)
- OSX 10.15.4

**Comment by JoshuaNitschke** [comment]
Might be failing the windows checks because vcpkg isn't installed?

**Comment by dginev** [comment]
Perfect, thanks @JoshuaNitschke !

I just updated appveyor, and will fix the builds in master, your code already looks spot on, thanks for setting everything up. Once I get appveyor happy I'll ship a minor release of the crate.

**Pull request merged**
